# info for run
code_root: null
integrations:
  wandb:
    active: True
    project: "vae_sketch2face"

# Dataset info
datasets:
  train: data.data_loader.dataset.DatasetTrain
  validation: data.data_loader.dataset.DatasetEval

data:
  data_root_face: /export/home/rhaecker/documents/sketch2face/data/data_sets/img_align_celeba/
  data_root_sketch: /export/home/haecker/documents/sketch2face/data/data_sets/full_numpy_bitmap_face.npy
  
  shuffle: True
  validation_split: 0.1
  transform:
    resolution: 64
    mirrow: True
    crop_offset: 10

# Meta Info
explanation: "VAE with reduce lr on faces."
debug_log_level: False
#CUDA_VISIBLE_DEVICES: 8

# Iterator info
iterator: iterator.iterator.Iterator
model: model.vae.VAE_Model

model_type: "face"
# face ; sketch

batch_size: 10
num_epochs: 10

optimization:
  reduce_lr: 0.7

losses:
  reconstruction_loss: "L2"

# Model info
activation_function: "ReLU"
learning_rate: 0.0001
#log_freq: 2000

variational:
  sigma: True

  # Conv parameters
conv:
  n_channel_start: 32
  n_channel_max: 256
  sketch_extra_conv: 1
  face_extra_conv: 0
batch_norm: True
random_seed: 10