# info for run
code_root: null
integrations:
  wandb:
    active: True
    project: "Debug!"

# Dataset info
datasets:
  train: data.data_loader.dataset.DatasetTrain
  validation: data.data_loader.dataset.DatasetEval

  data:
  data_root_face: /export/home/rhaecker/documents/src/20_ss/deep_vision/sketch2face/data/data_sets/faces/
  data_root_sketches: /export/home/rhaecker/documents/src/20_ss/deep_vision/sketch2face/data/data_sets/sketches/
  validation_split: 0.1
  test_split: 0.1
  transform:
    resolution: 64
    mirrow: True
    crop_offset: 5

# Meta Info
explanation: "Test only for debugging."
debug_log_level: True
#CUDA_VISIBLE_DEVICES: 8

# Iterator info
iterator: iterator.iterator.Iterator
model: model.vae.VAE_Model
batch_size: 10
num_epochs: 2

losses:
  reconstruction_loss: "L2"
  KLD_loss:
    start_step: 60000
    width: 500
    amplitude: 0.001

# Model info
activation_function: "ReLU"
learning_rate: 0.0001
weight_decay: 0.000001 
#log_freq: 2000

variational:
  sigma: True

  # Conv parameters
conv:
  n_channel_start: 32
  n_channel_max: 256
  final_layer: True
batch_norm: True