# info for run
code_root: null
# log to weights and biases
integrations:
  wandb:
    active: False
    project: "sketch2face"

# Dataloader
datasets:
  train: data.data_loader.dataset.DatasetTrain
  validation: data.data_loader.dataset.DatasetEval
# info for data loader
data:
  # path to datasets used in the data loader
  data_root_face: /export/home/rhaecker/documents/sketch2face/data/data_sets/img_align_celeba/
  data_root_sketch: /export/home/rhaecker/documents/sketch2face/data/data_sets/full_numpy_bitmap_face.npy
  # shuffel dataset indices
  shuffle: True
  # shuffel dataset indices
  validation_split: 0.1
  # info for transformation of only face data
  transform:
    resolution: 64
    mirrow: True
    crop_offset: 5

# optinal Meta Info
explanation: "First cycle gan with accuracy."
# log level of logger
debug_log_level: False

# Iterator info
iterator: iterator.cycle_gan_iterator.Iterator
model: model.cycle_gan.CycleGAN_Model

model_type: "sketch2face"
# face ; sketch

batch_size: 10
num_epochs: 10

optimization:
  reduce_lr: 0.7
  D_accuracy: [0.67,0.67]
  D_lr_factor: 0.1

losses:
  reconstruction_loss: "L2"
  reconstruction_weight: 5.0
  adversarial_loss: "BCE"
  adversarial_weight: 1.0

# Model info
activation_function: "ReLU"
learning_rate: 0.00005
#log_freq: 2000

variational:
  sigma: True


  # Conv parameters
conv:
  n_channel_start: 32
  n_channel_max: 512
  sketch_extra_conv: 1
  face_extra_conv: 1
batch_norm: True
random_seed: 10