# info for run
code_root: null
integrations:
  wandb:
    active: True
    #project: "Debug!"
    project: "sketch_or_face"
    entity: "chacker"

# Dataset info
datasets:
  train: data.data_loader.dataset.DatasetTrain
  validation: data.data_loader.dataset.DatasetEval

data:
  data_root_face: /export/home/rhaecker/documents/sketch2face/data/data_sets/img_align_celeba/
  data_root_sketch: /export/home/rhaecker/documents/sketch2face/data/data_sets/full_numpy_bitmap_face.npy
  
  shuffle: True
  validation_split: 0.1
  test_split: 0.1
  transform:
    resolution: 64
    mirrow: False
    crop_offset: 0

# Meta Info
explanation: "GAN sketch."
debug_log_level: False
#CUDA_VISIBLE_DEVICES: 8

# Iterator info
iterator: iterator.gan_iterator.Iterator
model: model.cycle_gan2.CycleGAN_Model
#load pretrained vaes for cycle gan model
#load_models:
#  face_path:
#  sketch_path:


model_type: "sketch"
# face ; sketch

batch_size: 128
num_steps: 50000

batch_norm: True
random_seed: 10

optimization:
  reduce_lr: 0.8
  D_accuracy: 1.0
  D_lr_factor: 2

bias:
  dec: False
  enc: False

dropout:
  dec_rate: 0
  enc_rate: 0
  disc_rate: 0

losses:
  reconstruction_loss: "L2"
  reconstruction_weight: 5.0
  adversarial_loss: "BCE"
  adversarial_weight: 1.0
  kld:
    weight: 20.0
    delay: 10000
    slope_steps: 2000

# Model info
activation_function: "ReLU"
learning_rate: 0.0001
#log_freq: 2000

variational:
  sigma: True
  num_latent_layer: 0
  # Conv parameters
conv:
  n_channel_start: 256
  n_channel_max: 1024
  sketch_extra_conv: 0
  face_extra_conv: 0
  kld:
    weight: 20.0
    delay: 10000
    slope_steps: 2000
  
latent_dim: 512